#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../lib" >/dev/null 2>&1 && pwd )"
source "$SCRIPT_DIR"/worktree_lib.bash

function main() {
  _worktree_exists

  echo "--prefix=$(_worktree_prefix)"
}

main